$(function(){
var navData=[
			{
				title:['家用电器'],
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'五金家装',
						content:['家具五金', '电动工具', '手动工具', '厨卫五金', '电工电料','监控安防']
					},
					{
						title:'大家电',
						content:["平板电视", "空调冰箱", "洗衣机", "家庭影院", "烟机/灶具", "热水器", "消毒柜/洗碗机", "冷柜/冰吧"]
					},
					{
						title:'生活电器',
						content:["电风扇","净化器","加湿器","吸尘器","挂烫机/熨斗","取暖电器","饮水机","其它生活电器"]
					},
					{
						title:'厨房电器',
						content:["电饭煲","微波炉","电磁炉","电饼铛/烧烤盘","电炖锅","果蔬解毒机","养生壶/煎药壶","其它厨房电器"]
					},{
						title:'个护健康',
						content:["剃须刀","电吹风","按摩椅","足浴盆","健康秤/厨房秤","血糖仪","计步器/脂肪检测","其它健康电器"]
					}
				]
			},
			{
				title:['手机、数码、通信'],
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'热卖手机',
						content:['三星盖乐世', 'iPhone', '小米特供', '魅族手机', '华为荣耀', '联通4G', '电信4G','移动4G']
					},
					{
						title:'手机配件',
						content:["电池", "移动电源", "蓝牙耳机", "充电器", "创意配件", "手机饰品", "手机耳机", "保护套"]
					},
					{
						title:'数码影音',
						content:["数码相机","单反相机","拍立得","运动相机","摄像机","户外器材","数码相框","影棚器材"]
					},
					{
						title:'智能设备',
						content:["智能手环","智能手表","智能眼镜","运动跟踪器","智能家居","体感车"]
					}
				]
			},
			{
				title:['家居、家具、家装、厨具'],
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'家纺',
						content:['床品套件','被子','蚊帐','凉席','床单被罩','毛巾浴巾','床垫/床褥','窗帘/窗纱']
					},{
						title:'家具',
						content:['卧室家具','客厅家具','餐厅家具','书房家具','储物家具','阳台/户外','沙发','鞋架/衣帽架']
					},{
						title:'厨具',
						content:['烹饪锅具','刀剪菜板','厨房配件','水具酒具','餐具','茶具/咖啡具']
					},{
						title:'灯具',
						content:['台灯', '吸顶灯', '筒灯射灯', 'LED灯','落地灯', '应急灯/手电', '装饰灯', '吊灯']
					},{
						title:'家装软饰',
						content:['桌布/罩件','地毯地垫','沙发垫套/椅垫','帘艺隔断','相框/照片墙','装饰字画','墙贴/装饰贴','摆件花瓶']
					},{
						title:'生活日用',
						content:['收纳用品','雨伞雨具','浴室用品','缝纫/针织用品','洗晒/熨烫','净化除味']
					}
				]
			},
			{
				title:['电脑、办公'],
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'销售管理',
						content:['销售主管', '销售经理', '销售总监', '区域总监', '销售副总', '店长', '招商经理']
					},
					{
						title:'坐家等客',
						content:["电话销售", "渠道销售", "促销员", "二手房销售", "4S店销售", "会议营销", "奢侈品销售", "营业员"]
					},
					{
						title:'往外跑的',
						content:["电商销售","大客户销售","销售工程师","地产销售","金融销售","医药代表","业务员"]
					},
					{
						title:'客服',
						content:["售前服务","售后服务","技术支持","呼叫中心"]
					}
				]
			},
			{
				title:'男装、女装、内衣、珠宝',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'财务',
					    content:['首席财务官 CFO','财务总监',	'财务经理',	'财务/总帐主管','成本会计','固定资产会计','出纳','财务/会计助理','会计文员','财务分析经理/主管','财务分析员']
					},
					{
					},
					{
						title:'审计税务',
					    content:['审计经理/主管','审计专员/助理',	'税务经理/税务主管',	'税务专员/助理',	'统计员']
					}
				]
			},
				{
				title:'个护化妆、清洁用品',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'金融',
					    content:['证券/期货/外汇经纪人','证券分析师',	'股票/期货操盘手',	'金融/经济研究员','投资/基金项目经理','投资/理财顾问','投资银行业务','融资经理/融资主管','融资专员','拍卖/担保/典当业务','金融产品经理','投资银行财务分析','风险管理/控制']
					},
					{
					},
					{
						title:'银行',
					    content:['行长/副行长','资产评估/分析','风险控制','进出口/信用证结算','清算人员','外汇交易','高级客户经理/客户经理','客户主管/专员','信贷管理','银行柜员','银行卡、电子银行业务推广','个人业务部门经理/主管','个人业务客户经理','公司业务部门经理/主管','公司业务客户经理','综合业务经理/主管','综合业务专员','信审核查','营业部大堂经理','银行客户总监']
					},
					{
						title:'保险',
					    content:['保险精算师','保险产品开发/项目策划','保险业务经理/主管','保险代理/经纪人/客户经理','理财顾问/财务规划师','储备经理人','保险核保','保险理赔','保险客户服务/续期管理','保险培训师','保险内勤','契约管理']
					}
				]
			},
			{
				title:'鞋靴、箱包、钟表、奢侈品',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'生产营运',
						content:['']
					},
					{
						title:'质量安全',
						content:['']
					},
					{
						title:'机械能源',
						content:[''	]
					},
					{
						title:'汽车制造',
						content:['']
					},
					{
						title:'汽车销售',
						content:['']
					},
					{
						title:'服装纺织',
						content:['']
					},
					{
						title:'贸易',
						content:['']
					}
				]
			},
			{
				title:'运动户外',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'制药医疗器械',
						content:['']
					},
					{
						title:'化工',
						content:['']
					},
					{
						title:'医疗护理',
						content:['']
					}
				]
			},
			{
				title:'汽车、汽车用品',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'广告',
						content:['']
					},
					{
						title:'公关媒介',
						content:['']
					},
					{
						title:'市场营销',
						content:['']
					},
					{
						title:'影视媒体',
						content:['']
					},
					{
						title:'写作出版',
						content:['']
					},
					{
						title:'艺术设计',
						content:['']
					}
				]
			},
			{
				title:'母婴、玩具乐器',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
						{
						title:'建筑装潢/市政建设',
						content:['']
					},
					{
						title:'房地产开发/销售',
						content:['']
					},
					{
						title:'房地产中介',
						content:['']
					},
					{
						title:'物业管理',
						content:['']
					}
				]
			},
			{
				title:'食品、酒类、生鲜、特产',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'酒类饮料',
						content:['酒水', '冲调饮品', '饮料饮品', '茗茶']
					},
					{
						title:'进口水果',
						content:["释迦芭乐", "樱桃车厘子", "芒果桃李", "龙眼荔枝", "提子葡萄", "奇异果猕猴桃", "凤梨蓝莓", "榴莲山竹"]
					},
					{
						title:'糖果巧克力',
						content:["巧克力","口香糖","棒棒糖","软糖","奶糖","QQ糖","果冻"]
					},
					{
						title:'牛奶乳品',
						content:["常温奶","乳饮料","儿童奶","酸奶","豆奶","低脂奶","全脂奶","成人奶粉"]
					},{
						title:'坚果炒货',
						content:["核桃","夏威夷果","碧根果","开心果","腰果","瓜子","花生","杏仁"]
					},{
						title:'蜜饯果干',
						content:["红枣","莓类","葡萄干","芒果干","香蕉干","山楂片","橄榄","其他"]
					},{
						title:'特产'
					}
				]
			},
			{
				title:'营养保健',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'咨询/顾问',
						content:['']
					},
					{
						title:'律师/法务/合规',
						content:['']
					},
					{
						title:'教师',
						content:['']
					},
					{
						title:'培训',
						content:['']
					},
					{
						title:'科研人员',
						content:['']
					}
				]
			},
			{
				title:'图书、音像、电子书',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
						{
						title:'餐饮/娱乐',
						content:['']
					},
					{
						title:'酒店/旅游',
						content:['']
					},
					{
						title:'美容/健身/体育',
						content:['']
					},
					{
						title:'百货/连锁/零售服务',
						content:['']
					},
					{
						title:'交通运输服务',
						content:['']
					},
					{
						title:'保安/家政',
						content:['']
					}
				]
			},
			{
				title:'彩票、旅行、充值、票务',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'公务员',
						content:['']
					},
					{
						title:'翻译',
						content:['']
					},
					{
						title:'在校学生',
						content:['']
					},
					{
						title:'储备干部/培训生/实习生',
						content:['']
					},
					{
						title:'环保',
						content:['']
					},
					{
						title:'农林牧渔',
						content:['']
					},
					{
						title:'兼职',
						content:['']
					}
				]
			},
			{
				title:'理财、众筹、白条、保险',
				id:'speedMenu'+parseInt(Math.random()*1000),
				content:[
					{
						title:'总监级',
						content:['运营总监','营销总监',	'销售总监',	'生产总监',	'制片总监',	'拍摄总监',	'创意总监',	'技术总监',	'执行总监',	'财务总监',	'设计总监']
					},
					{
						title:'经理级',
						content:['运营经理','营销经理',	'销售经理',	'生产经理',	'制片经理',	'拍摄经理',	'创意经理',	'技术经理',	'执行经理',	'财务经理',	'设计经理']
					}
				]
			}
		];
		ko.applyBindings({navData:navData})
	})